#:schema ./schema.json

id = "plausible"
name = "Plausible"
description = "Plausible is intuitive, lightweight and open source web analytics."
icon = "https://asset.brandfetch.io/id2ceYC7ck/idkMMiHKhK.png"
templateURL = "https://zeabur.com/templates/SF91ZK"
tags = ["Analytics", "Web Analytics", "Google Analytics Alternative"]

[source]
image = "plausible/analytics:v2.0"
command = ["sh"]
args = ["-c", "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"]

[[ports]]
id = "web"
port = 8000
type = "HTTP"

[env]
BASE_URL = { default = "${ZEABUR_WEB_URL}" }
SECRET_KEY_BASE = { default = "${PASSWORD}${PASSWORD}${PASSWORD}${PASSWORD}" }
DATABASE_URL = { default = "postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}" }
CLICKHOUSE_DATABASE_URL = { default = "http://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse.zeabur.internal:8123/${CLICKHOUSE_DB}" }
