#:schema ./schema.json

id = "postgresql"
name = "PostgreSQL"
description = "PostgreSQL is a powerful, open source object-relational database system."
icon = "https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg"
docs = "https://zeabur.com/docs/marketplace/postgresql"
tags = ["Database"]

[source]
image = "postgres:16"
command = ["docker-entrypoint.sh", "-c", "config_file=/etc/postgresql/postgresql.conf"]

[[ports]]
id = "database"
port = 5432
type = "TCP"

[[volumes]]
id = "data"
dir = "/var/lib/postgresql/data"

[env]
POSTGRES_USER = { default = "root" }
POSTGRES_DB = { default = "zeabur" }

PGDATA = { default = "/var/lib/postgresql/data/pgdata" }

POSTGRES_HOST = { default = "${CONTAINER_HOSTNAME}", expose = true, readonly = true }
POSTGRES_PORT = { default = "${DATABASE_PORT}", expose = true, readonly = true }
POSTGRES_USERNAME = { default = "${POSTGRES_USER}", expose = true, readonly = true }
POSTGRES_PASSWORD = { default = "${PASSWORD}", expose = true }
POSTGRES_DATABASE = { default = "${POSTGRES_DB}", expose = true, readonly = true }

POSTGRES_CONNECTION_STRING = { default = "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}", expose = true, readonly = true }
POSTGRES_URI = { default = "${POSTGRES_CONNECTION_STRING}", expose = true, readonly = true }

[[instructions]]
type = "TEXT"
title = "Connection String"
content = "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${PORT_FORWARDED_HOSTNAME}:${DATABASE_PORT_FORWARDED_PORT}/${POSTGRES_DATABASE}"

[[instructions]]
type = "TEXT"
title = "PostgreSQL Connect Command"
content = "psql \"postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${PORT_FORWARDED_HOSTNAME}:${DATABASE_PORT_FORWARDED_PORT}/${POSTGRES_DATABASE}\""

[[instructions]]
type = "TEXT"
title = "PostgreSQL username"
content = "${POSTGRES_USERNAME}"
category = "Credentials"

[[instructions]]
type = "PASSWORD"
title = "PostgresSQL password"
content = "${POSTGRES_PASSWORD}"
category = "Credentials"

[[instructions]]
type = "TEXT"
title = "PostgresSQL database"
content = "${POSTGRES_DATABASE}"
category = "Credentials"

[[instructions]]
type = "TEXT"
title = "PostgreSQL host"
content = "${PORT_FORWARDED_HOSTNAME}"
category = "Hostname & Port"

[[instructions]]
type = "TEXT"
title = "PostgreSQL port"
content = "${DATABASE_PORT_FORWARDED_PORT}"
category = "Hostname & Port"

[[configs]]
path = "/etc/postgresql/postgresql.conf"
template = """\
# https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/postgresql.conf.sample
listen_addresses = '*'
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix
max_wal_size = 1GB
min_wal_size = 80MB
log_timezone = 'Etc/UTC'
datestyle = 'iso, mdy'
timezone = 'Etc/UTC'
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
default_text_search_config = 'pg_catalog.english'
"""
