#:schema ./schema.json

id = "rsstt"
name = "RSStT"
icon = "https://github.com/Rongronggg9/RSS-to-Telegram-Bot/raw/dev/docs/resources/RSStT_icon.svg"
description = "A Telegram RSS bot that cares about your reading experience."
tags = ["RSS", "Bot", "Automation", "Telegram"]

[source]
image = "rongronggg9/rss-to-telegram:dev"

[[ports]]
id = "web"
port = 8080
type = "HTTP"

[[volumes]]
id = "data"
dir = "/app/config"

[env]
TOKEN = { required = true }
MANAGER = { required = true }
TELEGRAPH_TOKEN = { required = true }
DATABASE_URL = { default = "${POSTGRES_CONNECTION_STRING}" }
