#:schema ./schema.json

id = "statusnook"
name = "Statusnook"
description = "Effortlessly deploy a status page and start monitoring endpoints in minutes."
icon = "https://icons.zeabur.com/statusnook.png"
tags = ["Monitoring"]
templateURL = "https://zeabur.com/templates/STATOK"

[source]
image = "goksan/statusnook:latest"

[[ports]]
id = "web"
port = 8000
type = "HTTP"

[[volumes]]
id = "data"
dir = "/app/statusnook-data"
