name: Check if definition matches schema

on:
  push:
  pull_request:

jobs:
  check-prebuilts:
    name: Check prebuilts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install jsonschema
      - run: python3 ../scripts/check-prebuilts.py
        working-directory: prebuilts

  check-templates:
    name: Check templates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/neilpa/yajsv@latest
      - run: yajsv -s schema/template.json -r 'schema/*.json' 'templates/**/*.yaml'

  # check-prebuilts-references:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.12'
  #     - run: python3 ../scripts/check-prebuilts-variable-refs.py
  #       working-directory: prebuilts
